apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: lugx-game-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gamedb-secret
                  key: root_username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gamedb-secret
                  key: root_password
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "game_db"

---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: ClusterIP
  selector:
    app: game
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
