apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
type: Opaque
data:
  clickhouse_url: aHR0cDovL215LWh5cGVyZHgtaGR4LW9zcy12Mi1jbGlja2hvdXNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6ODEyMwo=
  clickhouse_user: ZGVmYXVsdA==
  clickhouse_password: ""

  aws_access_key_id: QUtJQVEyV0FPVkxaTEVITTMyVVo=
  aws_secret_access_key: WTFQVmJZMGwwZVFBTTRpNGVwWHY0NGxRUHovV3UreTl5N1ArSWZyNg==
  aws_region: dXMtZWFzdC0y
  s3_bucket_name: c2FuZGFsaS10ZW1w