apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_ANALYTICS_API
          value: "/api/analytics"
        - name: REACT_APP_GAME_API
          value: "/api/games"
        - name: REACT_APP_ORDER_API
          value: "/api/orders"
        - name: REACT_APP_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: admin_api_key

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
